model:
    checkpoint: models/pretrained_Pocket2Mol.pt

sample:
  seed: 2024
  num_samples: 20
  beam_size: 50
  max_steps: 20
  threshold:
    focal_threshold: 0.5
    pos_threshold: 0.25
    element_threshold: 0.3
    hasatom_threshold: 0.6
    bond_threshold: 0.4
  guided:
    enabled: true
    qed_w: 1.0
    sa_w: 1.0
    lam: 3
    diversity_w: 0.8
  relax_output: true
